# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

DESTINATIONS=
"\
-destination 'generic/platform=iOS' \
-destination 'generic/platform=iOS Simulator' \
-destination 'generic/platform=tvOS' \
-destination 'generic/platform=tvOS Simulator' \
-destination 'generic/platform=watchOS' \
-destination 'generic/platform=watchOS Simulator' \
-destination 'generic/platform=macOS' \
-destination 'generic/platform=macOS,variant=Mac Catalyst'\
"

lane :build_debug do |options|

  xcodebuild(
    scheme: "SwiftFlex",
    xcargs: "\
clean \
-configuration debug \
#{DESTINATIONS} \
-xcconfig SwiftFlex.xcconfig\
"
  )

  xcodebuild(
    scheme: "SwiftFlex",
    xcargs: "\
build \
-configuration debug \
#{DESTINATIONS} \
-xcconfig SwiftFlex.xcconfig\
"
  )

end

lane :build_release do |options|

  xcodebuild(
    scheme: "SwiftFlex",
    xcargs: "\
clean \
-configuration release \
#{DESTINATIONS} \
-xcconfig SwiftFlex.xcconfig\
"
  )

  xcodebuild(
    scheme: "SwiftFlex",
    xcargs: "\
build \
-configuration release \
#{DESTINATIONS} \
-xcconfig SwiftFlex.xcconfig\
"
  )

end

lane :generate_xcodeproj do |options|
  spm(
    command: "generate-xcodeproj",
    xcconfig: "SwiftFlex.xcconfig"
  )
end
